import React from 'react'
import Head from 'next/head'
import NavBar from '../components/NavBar'
import BackToTop from '../components/BackToTop'
import Summary from '../components/Summary'
import WorkEd from '../components/WorkEd'
import ContactForm from '../components/ContactForm'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
//import styles from '../../styles/Home.module.css'
import {
  makeStyles,
  CssBaseline,
  Container,
  Grid,
  Paper,
  Box,
  Typography
} from '@material-ui/core'

const useStyles = makeStyles((theme) => ({
  paper: {
    padding: theme.spacing(3)
  },
  card: {
    textAlign: 'justify'
  },
  box: {
    margin: '0 auto',
    width: '55%'
  }
}));

export default function Home() {
  const classes = useStyles();

  const headers = {
    summary: 'Summary',
    projects: 'Projects',
    skills: 'Technical Skills',
    timeline: 'Timeline',
    contact: 'Contact Me'
  }

  return (
    <React.Fragment>
      <CssBaseline />
      <Container maxWidth="md">
        <Head>
          <title>Resume</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        </Head>

        <main>          
          <Paper className={classes.paper} elevation={1}>
            <NavBar headers={headers} />
            <Box
              className={classes.box}
              bgcolor="text.primary" 
              color="background.paper"
            >
              <Typography variant="h3" align="center">
                JOHNSON CHUNG
              </Typography>
            </Box>
            <Typography variant="h4" align="center" gutterBottom>
              Resume
            </Typography>
            <Grid
              container
              spacing={3}
              justify="space-evenly"
              alignItems="flex-start"
            >
              <Grid item xs={12}>
                <Summary title={headers.summary} />
              </Grid>
              <Grid item xs={12}>
                <Projects title={headers.projects} /> 
              </Grid>
              <Grid item xs={12}>                
                <Skills title={headers.skills} />              
              </Grid>
              <Grid item xs={12}>                
                <WorkEd title={headers.timeline} />
              </Grid>
              <Grid item xs={12}>
                <ContactForm title={headers.contact} />             
              </Grid>
            </Grid>
          </Paper>
        </main>

        <footer>
          <BackToTop />
        </footer>
      </Container>      
    </React.Fragment>
  )
}
