import React from 'react'
import Head from 'next/head'
import Summary from '../components/Summary'
import WorkEd from '../components/WorkEd'
import ContactForm from '../components/ContactForm'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
//import styles from '../../styles/Home.module.css'
import {
  makeStyles,
  CssBaseline,
  Container,
  Grid,
  Paper,
  Typography
} from '@material-ui/core'

const useStyles = makeStyles((theme) => ({
  paper: {
    padding: theme.spacing(3)
  },
  card: {
    textAlign: 'justify'
  }
}));

export default function Home() {
  const classes = useStyles();

  return (
    <React.Fragment>
      <CssBaseline />
      <Container maxWidth="md">
        <Head>
          <title>Resume</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        </Head>

        <main>
          <Paper className={classes.paper} elevation={1}>
            <Typography 
              gutterBottom 
              variant="h3" 
              align="center"
            >
              Resume
            </Typography>
            <Grid
              container
              spacing={3}
              justify="space-evenly"
              alignItems="flex-start"
            >
              <Grid item xs={12}>
                <Summary />
              </Grid>
              <Grid item xs={12}>
                <Projects /> 
              </Grid>
              <Grid item xs={12}>                
                <Skills />              
              </Grid>
              <Grid item xs={12}>                
                <WorkEd />
              </Grid>
              <Grid item xs={12}>
                <ContactForm />             
              </Grid>
            </Grid>
          </Paper>
        </main>

        <footer>
          
        </footer>
      </Container>
    </React.Fragment>
  )
}
